# Generated by Django 4.2.3 on 2023-07-05 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favorite_list',
            field=models.ManyToManyField(blank=True, related_name='favorited_for', to='api.recipe'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='shopping_list',
            field=models.ManyToManyField(blank=True, related_name='added_to_cart', to='api.recipe'),
        ),
    ]
