# Generated by Django 4.2.3 on 2023-07-07 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_profile_favorite_list_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='is_favorited',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='is_in_shopping_cart',
        ),
    ]
