# Generated by Django 4.2.3 on 2023-07-22 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_recipe_options_recipe_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
        migrations.DeleteModel(
            name='RoleUser',
        ),
    ]
